firstname = input("What is your firstname?: ")
lastname = input ("What is your lastname? : ")
hobbit = input ("What is your favorit hobbit?: ")
age = input(" input your age? : ")
language = input ("input your languages please? : ")